services:
    nginx:
        image: nginx:latest
        environment:
            ADMIN_SERVER_NAME: ${ADMIN_SERVER_NAME}
            APP_SERVER_NAME: ${APP_SERVER_NAME}

        configs:
            - source: nginx_conf
              target: /etc/nginx/nginx.conf
            - source: nginx_admin_template
              target: /etc/nginx/templates/admin.conf.template
            - source: nginx_app_template
              target: /etc/nginx/templates/app.conf.template

        secrets:
            - cert.crt
            - cert.key
        networks:
            - intranet
        ports:
            - "80:80"
            - "443:443"
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]

    redis:
        image: redis:latest
        volumes:
            - redis_data:/data
            - ./config/redis/entrypoint.sh:/usr/local/bin/entrypoint.sh
        configs:
            - source: redis_conf_template
              target: /usr/local/etc/redis/redis.conf.template
        entrypoint: ["sh", "/usr/local/bin/entrypoint.sh"]
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        secrets:
            - redis_user
            - redis_password
        networks:
            - intranet
        ports:
            - "6385:6385"
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    admin:
        image: ${REGISTRY_URL}/admin:dev
        networks:
            - intranet
        environment:
            DEBUG: 0
            ALLOWED_HOSTS: ${ADMIN_SERVER_NAME}
            CSRF_TRUSTED_ORIGINS: https://${ADMIN_SERVER_NAME}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            APP_DB_NAME: ${APP_DB_NAME}
            DJANGO_DB_NAME: ${DJANGO_DB_NAME}
            AWS_S3_USE_SSL: 1
            AWS_S3_URL_PROTOCOL: https
            AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
            APP_SERVICE_URL: http://app:3000
            SPORTS_API_URL: ${SPORTS_API_URL}
            
        secrets:
            - django_secret_key
            - db_django_user
            - db_django_password
            - django_superuser_email
            - django_superuser_username
            - django_superuser_password
            - aws_s3_access_key_id
            - aws_s3_secret_access_key
            - cache_invalidate_key
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    app:
        image: ${REGISTRY_URL}/app:dev
        networks:
            - intranet
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            APP_DB_NAME: ${APP_DB_NAME}
            REDIS_HOST: redis
            REDIS_PORT: 6385
            SPORTS_API_URL: ${SPORTS_API_URL}
            NEXT_PUBLIC_S3_ROOT: ${NEXT_PUBLIC_S3_ROOT}

        secrets:
            - db_app_user
            - db_app_password
            - redis_user
            - redis_password
            - cache_invalidate_key
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

configs:
    # Nginx
    nginx_conf:
        file: ./config/nginx/nginx.conf
    nginx_admin_template:
        file: ./config/nginx/templates/admin.conf.template
    nginx_app_template:
        file: ./config/nginx/templates/app.conf.template

    # PostgreSQL
    postgresql_conf:
        file: ./config/postgres/postgresql.conf
    postgresql_init:
        file: ./config/postgres/init/01-init.sh

    # Redis
    redis_conf_template:
        file: ./config/redis/redis.conf.template

secrets:
    # AWS
    aws_s3_access_key_id:
        external: true
    aws_s3_secret_access_key:
        external: true

    # INTERSERVICE
    cache_invalidate_key:
        external: true

    # DB
    db_app_user:
        external: true
    db_app_password:
        external: true
    db_django_user:
        external: true
    db_django_password:
        external: true

    # Redis
    redis_user:
        external: true
    redis_password:
        external: true

    # Django
    django_secret_key:
        external: true
    django_superuser_email:
        external: true
    django_superuser_username:
        external: true
    django_superuser_password:
        external: true

    # SSL
    cert.crt:
        external: true
    cert.key:
        external: true

volumes:
    redis_data:

networks:
    intranet:
        external: true
