services:
    nginx:
        image: nginx:latest
        environment:
            ADMIN_SERVER_NAME: admin.fontv.clbots.ru
            APP_SERVER_NAME: app.fontv.clbots.ru

        configs:
            - source: nginx_conf
              target: /etc/nginx/nginx.conf
            - source: nginx_admin_template
              target: /etc/nginx/templates/admin.conf.template
            - source: nginx_app_template
              target: /etc/nginx/templates/app.conf.template

        secrets:
            - cert.crt
            - cert.key
        networks:
            - intranet
        ports:
            - "80:80"
            - "443:443"
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]

    db:
        image: postgres:17.2-bookworm
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
            APP_DB_NAME: fon_tv
            DJANGO_DB_NAME: fon_tv_django
        volumes:
            - db_data:/var/lib/postgresql/data
        configs:
            # - source: postgresql_conf
            #   target: /etc/postgresql.conf
            - source: postgresql_init
              target: /docker-entrypoint-initdb.d/01-init.sh
        secrets:
            - db_password
            - db_app_user
            - db_app_password
            - db_django_user
            - db_django_password
        networks:
            - intranet
        ports:
            - "5432:5432"
        command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "root"]
            interval: 5s
            timeout: 10s
            retries: 3
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]

    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        configs:
            - source: redis_conf
              target: /usr/local/etc/redis/redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    minio:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minioadmin
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first

    # admin:
    #     image: registry.fontv.clbots.ru:5000/admin:dev
    #     networks:
    #         - intranet
    #     environment:
    #         DB_HOST: db
    #         DB_PORT: 5432
    #         APP_DB_NAME: fon_tv
    #         DJANGO_DB_NAME: fon_tv_django
    #         AWS_S3_USE_SSL: true
    #         AWS_S3_URL_PROTOCOL: https
    #         AWS_S3_ENDPOINT_URL: https://fontv.clbots.ru:9000
    #         AWS_STORAGE_BUCKET_NAME: bucket
    #         APP_SERVICE_URL: http://app:3000
    #         SPORTS_API_URL: http://217.198.5.178:8081
            
    #     secrets:
    #         - db_django_user
    #         - db_django_password
    #         - django_superuser_email
    #         - django_superuser_username
    #         - django_superuser_password
    #         - aws_s3_access_key_id
    #         - aws_s3_secret_access_key
    #         - cache_invalidate_key
    #     deploy:
    #         mode: replicated
    #         replicas: 1
    #         update_config:
    #             parallelism: 1
    #             delay: 10s
    #             order: start-first

    # app:
    #     image: registry.fontv.clbots.ru:5000/app:dev
    #     networks:
    #         - intranet
    #     environment:
    #         DB_HOST: db
    #         DB_PORT: 5432
    #         APP_DB_NAME: fon_tv
    #         REDIS_HOST: redis
    #         REDIS_PORT: 6379
    #         SPORTS_API_URL: http://217.198.5.178:8081
    #         NEXT_PUBLIC_S3_ROOT: https://fontv.clbots.ru:9000/bucket/media

    #     secrets:
    #         - db_app_user
    #         - db_app_password
    #         - redis_user
    #         - redis_password
    #         - cache_invalidate_key
    #     deploy:
    #         mode: replicated
    #         replicas: 1
    #         update_config:
    #             parallelism: 1
    #             delay: 10s
    #             order: start-first

configs:
    # Nginx
    nginx_conf:
        file: ./config/nginx/nginx.conf
    nginx_admin_template:
        file: ./config/nginx/templates/admin.conf.template
    nginx_app_template:
        file: ./config/nginx/templates/app.conf.template

    # PostgreSQL

    # postgresql_conf:
    #     file: ./config/postgres/postgresql.conf
    postgresql_init:
        file: ./config/postgres/init/01-init.sh

    # Redis
    redis_conf:
        file: ./config/redis/redis.conf

secrets:
    # AWS
    aws_s3_access_key_id:
        external: true
    aws_s3_secret_access_key:
        external: true

    # INTERSERVICE
    cache_invalidate_key:
        external: true

    # DB
    db_password:
        external: true
    db_app_user:
        external: true
    db_app_password:
        external: true
    db_django_user:
        external: true
    db_django_password:
        external: true

    # Redis
    redis_user:
        external: true
    redis_password:
        external: true

    # Django
    django_superuser_email:
        external: true
    django_superuser_username:
        external: true
    django_superuser_password:
        external: true

    # SSL
    cert.crt:
        external: true
    cert.key:
        external: true

volumes:
    db_data:
    redis_data:
    minio_data:

networks:
    intranet:
        external: true
