#!/bin/bash
set -e

BACKEND_USER=$(cat /run/secrets/db_backend_user)
BACKEND_PASSWORD=$(cat /run/secrets/db_backend_password)
DJANGO_USER=$(cat /run/secrets/db_django_user)
DJANGO_PASSWORD=$(cat /run/secrets/db_django_password)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $BACKEND_USER WITH PASSWORD '$BACKEND_PASSWORD';
    CREATE USER $DJANGO_USER WITH PASSWORD '$DJANGO_PASSWORD';
	CREATE DATABASE $MAIN_DB_NAME;
    CREATE DATABASE $DJANGO_DB_NAME;

    \c $MAIN_DB_NAME
    GRANT ALL PRIVILEGES ON DATABASE $MAIN_DB_NAME TO $BACKEND_USER;
    GRANT ALL PRIVILEGES ON DATABASE $MAIN_DB_NAME TO $DJANGO_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $BACKEND_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $DJANGO_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $BACKEND_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DJANGO_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $BACKEND_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DJANGO_USER;
    SET TIMEZONE TO 'Europe/Moscow';

    \c $DJANGO_DB_NAME
    GRANT ALL PRIVILEGES ON DATABASE $DJANGO_DB_NAME TO $DJANGO_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $DJANGO_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DJANGO_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $DJANGO_USER;
    SET TIMEZONE TO 'Europe/Moscow';
EOSQL
