#!/bin/bash
set -e

APP_USER=app
APP_PASSWORD=app
DJANGO_USER=django
DJANGO_PASSWORD=django

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
    CREATE USER $DJANGO_USER WITH PASSWORD '$DJANGO_PASSWORD';
	CREATE DATABASE $APP_DB_NAME;
    CREATE DATABASE $DJANGO_DB_NAME;

    \c $APP_DB_NAME
    GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $APP_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $APP_USER;

    GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $DJANGO_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $DJANGO_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DJANGO_USER;

    -- Migrations are applied by Django, so we need to grant privileges for app user.
    ALTER DEFAULT PRIVILEGES FOR USER $DJANGO_USER IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO $APP_USER;

    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO $DJANGO_USER;

    SET TIMEZONE TO 'Europe/Moscow';

    \c $DJANGO_DB_NAME
    GRANT ALL PRIVILEGES ON DATABASE $DJANGO_DB_NAME TO $DJANGO_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $DJANGO_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $DJANGO_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO $DJANGO_USER;
    SET TIMEZONE TO 'Europe/Moscow';
EOSQL
