services:
    db:
        image: postgres
        volumes:
            - ./01-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            APP_DB_NAME: app
            DJANGO_DB_NAME: django

        restart: unless-stopped
        ports:
            - 5432:5432

    django:
        depends_on:
            - db
            - minio
        build: ../../admin
        volumes:
            - ./secrets/:/run/secrets
        environment:
            DB_HOST: db
            DB_PORT: 5432
            APP_DB_NAME: app
            DJANGO_DB_NAME: django
            AWS_S3_USE_SSL: false
            AWS_S3_URL_PROTOCOL: http
            AWS_S3_ENDPOINT_URL: http://host.docker.internal:9000
            AWS_STORAGE_BUCKET_NAME: bucket
        ports:
            - 8000:8000

    minio:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minioadmin
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data

    # app:
    #     depends_on:
    #         - django
    #     build: ../../app
    #     volumes:
    #         - ./secrets/:/run/secrets
    #     environment:
    #         DB_HOST: db
    #         DB_PORT: 5432
    #         APP_DB_NAME: app
    #     ports:
    #         - 3000:3000

volumes:
    minio_data:
